"""Update models to use modern SQLAlchemy 2.0 syntax

Revision ID: 98474272c984
Revises: cb2e89bc072b
Create Date: 2025-10-30 11:19:16.266734

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98474272c984'
down_revision: str | Sequence[str] | None = 'cb2e89bc072b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profiles', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
